

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - mynetwork

  onlinestoreapp:
    image: ${DOCKER_REGISTRY-}onlinestoreapp
    build:
      context: .
      dockerfile: OnlineStoreApp/Dockerfile
    container_name: onlinestoreapp
    ports:
      - "7124:8080"
    depends_on:
      - sqlserver
    networks:
      - mynetwork

networks:
  mynetwork:
  

volumes:
  sqlvolume: